### ISSUE TITLE
1)authentication  2) visiting root lists repos      Failure/Error: @user_data = JSON.parse(user.body)JSON::ParserError: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/rails-github-api#26] opened 2019-04-17 20:19 UTC

**Comment by drakeltheryuujin** [comment] 2019-07-01 15:48
Hi @ICanDoAllThingThroughChrist,
It appears this issue is either a duplicate of, or included in, an existing issue found here: #25 

If you believe this issue is not already expressed in an un-closed issue on the repo, please re-open and provide further detail.

As always, thanks for contributing! 💙

**Closed by drakeltheryuujin** 2019-07-01 15:48 UTC
